config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/destroy'

  get 'login'=> 'sessions#new', as: 'login'
  post 'login' => 'sessions#create'
  get 'logout'=> 'sessions#destroy', as:'logout'

  get 'register' => 'users#new', as: 'register'

  get 'show/new'

  get 'show/edit'

  resources :posts do
    post 'like' => 'posts#like', as: 'like'
  end

  resources :users, except:[:index]
    match '/' => 'posts#index', via: [:get, :posts], as: 'root'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes


  validates :body, presence: true
  validates :body, length: {minimum: 1, maximum: 140, message:'has too many characters(max 10)' }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :likes

  has_secure_password


  has_attached_file :avatar, styles: { medium: "300x300#", thumb: "150x150#" }, default_url: "/images/:style/profile.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def to_s
    return self.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  include SessionsHelper

  def current_user
    return User.find_by(id: session[:user_id])
  end

  def login_required
    if !current_user
      redirect_to login_path, notice: 'login required'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :like, :destroy]

  # GET /posts
  # GET /posts.json

  def index
    @post = Post.new
    @posts = Post.order("created_at DESC").all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create

    user = User.first
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Post was successfully created.' }
        format.js{}
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.js{}
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_url, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  #POST /posts/1/like
  def like
    #@post.likes.create(user: current_user)
    like = @post.likes.where(user: current_user).first_or_initialize

      if like.new_record?
        like.save
        #create like
        #@post.likes.create(user: current_user)
      else
        #delete like
        like.destroy
      end

      respond_to do |format|
          format.html {redirect_to request.referer}
      end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    if current_user == @post.user
      @post.destroy
        respond_to do |format|
          format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
          format.js {}
          format.json { head :no_content }
    end

  else #if surrent_user == @post
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.js {}
      format.json { head :no_content }
    end
  end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      id = params[:id]
      id ||= params[:post_id]
      @post = Post.find(id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body, )
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #login
  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user && @user.authenticate(params[:password])
      # login code
       session[:user_id] = @user.id

      #  redirect code
       redirect_to posts_url, notice: 'Login Successful!'
    else
      # wrong email/password
      render action: 'new' #text: 'login failed'

    end
  end

  #logout
  def destroy
    session[:user_id] = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :destroy]
  before_filter :login_required, only:[:edit, :update, :destroy]

  def show
    @posts = @user.posts.order('created_at DESC')
  end

  # GET /posts/new
  def new
    @user = User.new
  end

  # GET /posts/1/edit
  def edit
    @user = current_user
  end

  # POST /posts
  # POST /posts.json
  def create

    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id

        format.html { redirect_to posts_url, notice: 'user was successfully created.' }
        format.json { render :show, status: :created, location: @post }

      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'user was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
  end
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flutter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
  </head>

  <body>

  <header>
    <div class = "left">
        <h1> <%= link_to 'FLUTTER' , root_path %></h1>
    </div>

    <div class = "right">
      <% if current_user %>



        Welcome <%= current_user %>! <%= link_to '{logout}', logout_path %>

      <% else %>

        <%= link_to 'Sign Up', register_path %>
        <%= link_to 'Login', login_path %>
      <% end %>
    </div>
  </header>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post, remote: true) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="post" id="post-<%= post.id %>">
  <div class= "profile-section">
     <%= image_tag post.user.avatar.url(:thumb)%>
  </div>
  <div class="content">
    <%=post.body%>
    <p class= "author">
      <%= link_to post.user, user_path(post.user) %> -<%= post.created_at%>
    </p>
  </div>
  <div class="actions">
    <% if post.likes.where(user: current_user).first %>
      <%= link_to '', post_like_path(post_id: post.id), class: 'fa fa-heart', method: :post %>
    <% else %>
      <%= link_to '', post_like_path(post_id: post.id), class: 'fa fa-heart-o', method: :post %>
    <% end %>

    <% if current_user == post.user %>
      <%= link_to '', post, method: :delete, class: 'fa fa-trash', remote: true, data: { confirm: 'Are you sure?' }%>
    <% end %>
  </div>
</div>



<% if false%>
<tr>
  <td><%= post.body %></td>
   <td><%= link_to post.user.name, post.user%></td>

     <% if current_user == post.user %>
  <td><%= link_to 'Edit', edit_post_path(post) %></td>
 <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
 <% end %>
</tr>
<% end %>

app/views/posts/create.js.erb
$('.post-container').prepend("<%=j render partial:'post', locals: { post: @post} %>");

app/views/posts/destroy.js.erb
$('#post-<%= @post.id%>').slideUp();

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<img src="http://placehold.it/950x150">

<% if current_user %>
<%= render partial: 'form', locals: { post: @post } %>
<% end %>


<div class="post-container">
  <% @posts.each do |post| %>
    <%= render partial: 'post', locals: { post: post } %>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/edit.html.erb
<h1>Edit <%= @user.name %></h1>

<%= form_for(@user, html: {multipart: true}) do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email%>

<%= f.label :avatar, "Your Face" %>
<%= f.file_field :avatar %>

<%= f.label :password %>
<%= f.password_field :password%>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>


<%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h1>Create a New User</h1>

<%= form_for(@user, html: {multipart: true}) do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email%>

<%= f.label :avatar, "Your Face" %>
<%= f.file_field :avatar %>

<%= f.label :password %>
<%= f.password_field :password%>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>


<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1> <%= @user.name %> </h1>

<% @posts.each do |post| %>

  <%= render partial: 'posts/post', locals: {post: post}%>

<%end%>